---
  - name: Launch an AWS EC2 Ubuntu Instance
    hosts: localhost 
#    connection: local
#    gather_facts: False
    pre_tasks:
      - include_vars: vars/vars.yml
    tags: provisioning
    
    # Task that will be used to Launch/Create an AWS EC2 Instance
    tasks:
      - name: Launch the new AWS EC2 Instance(s)
        local_action: ec2
                      group_id={{ security_group }}
                      instance_type={{ instance_type}}
                      image={{ image }}
                      wait=true
                      region={{ region }}
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2
      - name: Associate Elastic IP address to the newly launched AWS EC2 Instance(s)
        local_action: ec2_eip
                      ip={{ elastic_ip }}
                      device_id={{ item.id }}
                      region={{ region }}
        with_items: "{{ ec2.instances }}"
      - name: Add tag(s) to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Name: My_Ubuntu_Instance 
            Hostname: techoverlord
            auto:start: 00 08 * * 1-5
            auto:stop: 00 20 * * 1-5
            Owner: Tech-Overlord
            OS: Ubuntu 16.04 LTSs
      - name: Add the newly created AWS EC2 instance(s) to the local host group (located inside the directory)
        local_action: lineinfile
                      dest="./hosts"
                      regexp={{ elastic_ip }}
                      insertafter="[ec2]" line={{ elastic_ip }}
      - name: Wait for SSH to come up
        local_action: wait_for
                      host={{ elastic_ip }}
                      port=22
                      state=started